/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-24 12:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html :class=\"{ 'theme-dark': dark }\" x-data=\"data()\" lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>HomeOneHana::관리자모드</title>\r\n");
      out.write("	<script src=\"http://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css\" integrity=\"sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=\" crossorigin=\"anonymous\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/chat/chat.css\" />\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chat/sockjs.min.js\"></script>\r\n");
      out.write("    <script src=\"https://use.typekit.net/hoy3lrg.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		var user = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.loginVO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\r\n");
      out.write("		var userId = user.id\r\n");
      out.write("		var userNm = user.name\r\n");
      out.write("		var socketId = null\r\n");
      out.write("		var myUserId = null\r\n");
      out.write("		var myUserName = null\r\n");
      out.write("		var loanNm = null\r\n");
      out.write("		var loanLink = null\r\n");
      out.write("\r\n");
      out.write("		console.log(user)\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			try {\r\n");
      out.write("				Typekit.load({\r\n");
      out.write("					async : true\r\n");
      out.write("				});\r\n");
      out.write("			} catch (e) {\r\n");
      out.write("			}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chat/chat.js\"></script>\r\n");
      out.write("	<link rel='stylesheet prefetch'\r\n");
      out.write("	href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div\r\n");
      out.write("      class=\"flex h-screen bg-gray-50 dark:bg-gray-900\"\r\n");
      out.write("      :class=\"{ 'overflow-hidden': isSideMenuOpen }\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/sider.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("      <!-- Backdrop -->\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"flex flex-col flex-1 w-full\">\r\n");
      out.write("      	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("        <main  class=\"section\">\r\n");
      out.write(" 			<div class=\"container\" style=\"margin:auto;\">\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"divide\" class=\"row\">\r\n");
      out.write("                    <div id=\"customerInfo\" class=\"col-lg-6 m-15px-tb\">\r\n");
      out.write("                        <div id=\"customerInput\" class=\"resume-box\">\r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"boxTempl\" style=\"text-align:right; margin-top:10px;\">\r\n");
      out.write("                            	<select id=\"hana_loans\">\r\n");
      out.write("                            		<option value=\"우량주택전세론\">우량주택전세론</option>\r\n");
      out.write("                            		<option value=\"주택신보 전세자금대출\">주택신보 전세자금대출</option>\r\n");
      out.write("                            		<option value=\"하나 청년전세론\">하나 청년전세론</option>\r\n");
      out.write("                            		<option value=\"신혼부부전세론\">신혼부부전세론</option>\r\n");
      out.write("                            		<option value=\"하나 전세금안심대출\">하나 전세금안심대출</option>\r\n");
      out.write("                            		<option value=\"다둥이전세론\">다둥이전세론</option>\r\n");
      out.write("                            	</select>\r\n");
      out.write("                            	\r\n");
      out.write("                            </div>\r\n");
      out.write("                             <h1 id=\"LoanNameIn\"></h1>\r\n");
      out.write("                            <div style=\"margin-top:20px; margin-bottom:20px; padding:20px;\">\r\n");
      out.write("                            	\r\n");
      out.write("                            	<div class=\"boxTempl\">\r\n");
      out.write("                            		<h4>대출정보</h4>\r\n");
      out.write("	                            	<table class=\"tbl\" id=\"loaninfoTbl\">\r\n");
      out.write("	                            		<thead>\r\n");
      out.write("	                            			<tr>\r\n");
      out.write("		                            			<th>금리변동주기</th>\r\n");
      out.write("		                            			<th>기준금리</th>\r\n");
      out.write("		                            			<th>가산금리</th>\r\n");
      out.write("		                            			<th>최종금리</th>\r\n");
      out.write("	                            			</tr>\r\n");
      out.write("	                            		</thead>\r\n");
      out.write("	                            		<tbody>\r\n");
      out.write("	                            			<tr>\r\n");
      out.write("		                            			<td id=\"loan-changedt\">-</td>\r\n");
      out.write("		                            			<td id=\"loan-baserate\">-</td>\r\n");
      out.write("		                            			<td id=\"loan-addrate\">-</td>\r\n");
      out.write("		                            			<td id=\"loan-finalrate\">-</td>\r\n");
      out.write("	                            			</tr>\r\n");
      out.write("	                            		</tbody>\r\n");
      out.write("	                            	</table>\r\n");
      out.write("                            	</div>\r\n");
      out.write("                            	\r\n");
      out.write("                            	<div id=\"condition\" class=\"boxTempl\"></div>\r\n");
      out.write("                            	\r\n");
      out.write("                            	<div class=\"boxTempl\"style=\"margin-top:10px;text-align:center;\">\r\n");
      out.write("                           				<button id=\"sendLimit\">대출상품정보전송</button>\r\n");
      out.write("                           				<button id=\"linkSend\">대출링크전송</button></div>\r\n");
      out.write("                            	</div>\r\n");
      out.write("                        	\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"chatArea\" class=\"col-lg-6 m-15px-tb\">\r\n");
      out.write("                        <div class=\"resume-box\">\r\n");
      out.write("                            <!-- chatstart -->\r\n");
      out.write("                           	<div id=\"chatTing\">\r\n");
      out.write("                           		<div id=\"chattitle\">\r\n");
      out.write("                           			<h2 id=\"customs\">고객상담</h2>\r\n");
      out.write("                           		</div>\r\n");
      out.write("                           		<div id=\"chatContents\">\r\n");
      out.write("                           		");
      out.write("\r\n");
      out.write("                           		</div>\r\n");
      out.write("                           		<div id=\"sendArea\">\r\n");
      out.write("                           			<div id=\"textBox\"><input type=\"text\" id=\"msgs\" ></div>\r\n");
      out.write("                           			<div id=\"sendBtn\"><button><i class=\"fas fa-paper-plane fa-lg\"></i></button></div>\r\n");
      out.write("                           		</div>\r\n");
      out.write("                           	</div>    \r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("                            <!-- chat end -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <script>\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			var content = '<span class=\"absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg\" aria-hidden=\"true\"></span>'\r\n");
      out.write("			$(content).prependTo('#chatMenu')    	  \r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
