/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-21 01:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.subscription;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class subscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/윤소영/final-project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HomeOneHana/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629721598702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HomeOneHana::모의청약</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/top/menubg.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/subscription/subscription.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script \r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"limiter\">\r\n");
      out.write("			<div class=\"container-login100\">\r\n");
      out.write("				<div class=\"wrap-login100\">\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("	</header>\r\n");
      out.write("	<section>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\"> \r\n");
      out.write("			<div class=\"col-md-12 bgcol\">  \r\n");
      out.write("			    <div class=\"col-md-4\">      \r\n");
      out.write("			        <div class=\"portlet light profile-sidebar-portlet bordered\">\r\n");
      out.write("			            <div class=\"profile-usertitle\">\r\n");
      out.write("			                <div class=\"profile-usertitle-name\"> 모의청약 </div>\r\n");
      out.write("			                <div class=\"profile-usertitle-job\"> practice subscription </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			      \r\n");
      out.write("			            <div class=\"profile-usermenu\">\r\n");
      out.write("			                <ul class=\"nav\">\r\n");
      out.write("			                	\r\n");
      out.write("			                    <li class=\"active\">\r\n");
      out.write("			                    	<div>\r\n");
      out.write("			                        <a href=\"#\">\r\n");
      out.write("			                            <i class=\"icon-home\"></i> 지금바로 청약을 연습해보세요! </a>\r\n");
      out.write("			                    	</div>\r\n");
      out.write("			                    </li>\r\n");
      out.write("			                    \r\n");
      out.write("			                    <li>\r\n");
      out.write("			                        <a href=\"#\">\r\n");
      out.write("			                            <i class=\"icon-info\"></i> 행복주택 </a>\r\n");
      out.write("			                    </li>\r\n");
      out.write("			                    <li>\r\n");
      out.write("			                        <a href=\"#\">\r\n");
      out.write("			                            <i class=\"icon-info\"></i> 국민임대 </a>\r\n");
      out.write("			                    </li>\r\n");
      out.write("			                    <li>\r\n");
      out.write("			                        <a href=\"#\">\r\n");
      out.write("			                            <i class=\"icon-info\"></i> 전세임대 </a>\r\n");
      out.write("			                    </li>\r\n");
      out.write("			                    <li>\r\n");
      out.write("			                        <a href=\"#\">\r\n");
      out.write("			                            <i class=\"icon-info\"></i> 청약점수계산 </a>\r\n");
      out.write("			                    </li>\r\n");
      out.write("			                </ul>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <div class=\"col-md-8\"> \r\n");
      out.write("			        <div class=\"portlet light bordered\">\r\n");
      out.write("			            <div class=\"portlet-title tabbable-line\">\r\n");
      out.write("			                <div class=\"caption caption-md\">\r\n");
      out.write("			                    <i class=\"icon-globe theme-font hide\"></i>\r\n");
      out.write("			                    <span class=\"caption-subject font-blue-madison bold uppercase\">행복주택</span>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <div class=\"portlet-body\">\r\n");
      out.write("			                <div>\r\n");
      out.write("\r\n");
      out.write("			                \r\n");
      out.write("			                    <!-- Tab panes -->\r\n");
      out.write("			                    <div class=\"tab-content\">\r\n");
      out.write("			                        <div role=\"tabpanel\" class=\"tab-pane active\" id=\"home\">\r\n");
      out.write("			                            <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/subscription\">\r\n");
      out.write("			                              <div class=\"form-group\" >\r\n");
      out.write("			                                <label class=\"ititle\" >공급구분</label>\r\n");
      out.write("			                                	<ul class=\"nav btnBox\" id=\"inputcerti\">\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"대학생\" value=\"대학생\" name=\"certification\" ><label class=\"icontent\" for=\"대학생\"> 대학생</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"취업준비생\" value=\"취업준비생\" name=\"certification\" ><label class=\"icontent\" for=\"취업준비생\"> 취업준비생</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"청년\" value=\"청년\" name=\"certification\" ><label class=\"icontent\" for=\"청년\"> 청년</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"사회초년생\" value=\"사회초년생\" name=\"certification\" ><label class=\"icontent\" for=\"사회초년생\"> 사회초년생</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"신혼부부\"  value=\"신혼부부\" name=\"certification\" ><label class=\"icontent\" for=\"신혼부부\" > 신혼부부</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"예비신혼부부\" value=\"예비신혼부부\" name=\"certification\" ><label class=\"icontent\" for=\"예비신혼부부\"> 예비신혼부부</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"한부모가족\" value=\"한부모가족\" name=\"certification\" ><label class=\"icontent\" for=\"한부모가족\"> 한부모가족</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"고령자\" value=\"고령자\" name=\"certification\" ><label class=\"icontent\" for=\"고령자\"> 고령자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"주거급여수급자\" value=\"주거급여수급자\" name=\"certification\" ><label class=\"icontent\" for=\"주거급여수급자\"> 주거급여수급자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"산업단지근로자\" value=\"산업단지근로자\" name=\"certification\" ><label class=\"icontent\" for=\"산업단지근로자\"> 산업단지근로자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"1인창조기업\" value=\"1인 창조기업\" name=\"certification\" ><label class=\"icontent\" for=\"1인창조기업\"> 1인창조기업</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"해당지자체장추천창업자및예비창업자\" value=\"해당 지자체장 추천 창업자 및 예비 창업자\" name=\"certification\" ><label class=\"icontent\" for=\"해당지자체장추천창업자및예비창업자\"> 해당지자체장추천창업자및예비창업자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"지역전략산업종사자\" value=\"지역전략산업 종사자\" name=\"certification\" ><label class=\"icontent\" for=\"지역전략산업종사자\"> 지역전략산업종사자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"장기근속자\" value=\"장기근속자\" name=\"certification\" ><label class=\"icontent\" for=\"장기근속자\"> 장기근속자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"etc1\" value=\"위 공급구분에 해당하지 않는 임시사용자\" name=\"certification\" ><label class=\"icontent\" for=\"etc1\"> 위 공급구분에 해당하지 않는 임시사용자</label></li>\r\n");
      out.write("			                                		<li class=\"btnOutline\"><input type=\"radio\" onClick=\"getvalue(this.value)\" id=\"etc2\" value=\"위 공급구분에 해당하지 않는 기존거주자\" name=\"certification\" ><label class=\"icontent\" for=\"etc2\"> 위 공급구분에 해당하지 않는 기존거주자</label></li>\r\n");
      out.write("			                                	</ul>\r\n");
      out.write("			                              </div>\r\n");
      out.write("			                                <div id=\"ranking-group\">\r\n");
      out.write("			                                \r\n");
      out.write("			                                </div>\r\n");
      out.write("			                                <div id=\"insertdetailinfo\">\r\n");
      out.write("			                                	<div class=\"form-group\">\r\n");
      out.write("			                                		<div class=\"detailBox\">\r\n");
      out.write("			                                			<div class=\"detailtitle\">\r\n");
      out.write("			                                				<div class=\"ititle\">학교정보</div>\r\n");
      out.write("			                                			</div>\r\n");
      out.write("				                                		<table class=\"detailinfotbl\" id=\"schooltbl\">\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">학교명</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"schoolname\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">소재지</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" id=\"addr1\" name=\"schooladdr\"><input type=\"button\" class=\"detailbtn\" value=\"소재지검색\" onclick=\"execDaumPostcode()\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">학생분류</div></th>\r\n");
      out.write("				                                				<td>\r\n");
      out.write("				                                					<div class=\"radioBox\">\r\n");
      out.write("					                                					<div class=\"rdoBox\"><input type=\"radio\" id=\"재학생\" name=\"schooltype\" value=\"재학생\"><label for=\"재학생\"  class=\"ranktitle\"> 재학생</label></div>\r\n");
      out.write("						                                				<div class=\"rdoBox\"><input type=\"radio\" id=\"복학예정\" name=\"schooltype\" value=\"복학예정\"><label for=\"복학예정\"  class=\"ranktitle\"> 복학예정</label></div>\r\n");
      out.write("						                                				<div class=\"rdoBox\"><input type=\"radio\" id=\"입학예정\" name=\"schooltype\" value=\"입학예정\"><label for=\"입학예정\"  class=\"ranktitle\"> 입학예정</label></div>\r\n");
      out.write("					                                				</div>\r\n");
      out.write("					                                			</td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                		</table>\r\n");
      out.write("				                                	</div>\r\n");
      out.write("				                                		\r\n");
      out.write("				                                	<div class=\"detailBox\">	\r\n");
      out.write("				                                		<div class=\"detailtitle\">\r\n");
      out.write("			                                				<div class=\"ititle\">세대원정보</div>\r\n");
      out.write("					                                		<div class=\"isubtitle\">\r\n");
      out.write("					                                		<span>본인의 주민등록본에 등재된 세대원은 동일세대를, 등재되어있지 않은 세대원은 분리세대를 체크하세요.</span>\r\n");
      out.write("					                                		<input type=\"button\" class=\"detailbtn\" value=\"추가\"><input type=\"button\" class=\"detailbtn\" value=\"삭제\"></div>\r\n");
      out.write("			                                			</div>\r\n");
      out.write("				                                		<table class=\"detailinfotbl\" id=\"hometbl\">\r\n");
      out.write("				                                			<thead>\r\n");
      out.write("					                                			<tr>\r\n");
      out.write("					                                				<th><div class=\"icontent\">신청자와의 관계</div></th>\r\n");
      out.write("					                                				<th><div class=\"icontent\">성명</div></th>\r\n");
      out.write("					                                				<th><div class=\"icontent\">주민등록번호</div></th>\r\n");
      out.write("					                                				<th><div class=\"icontent\">신청자가 속한<br>세대주와의 관계</div></th>\r\n");
      out.write("					                                				<th><div class=\"icontent\">세대구분</div></th>\r\n");
      out.write("					                                			</tr>\r\n");
      out.write("				                                			</thead>\r\n");
      out.write("				                                			<tbody>\r\n");
      out.write("				                                				<tr>\r\n");
      out.write("				                                					<td>본인</td>\r\n");
      out.write("				                                					<td>박이름</td>\r\n");
      out.write("				                                					<td>951234-5678900</td>\r\n");
      out.write("				                                					<td><select>\r\n");
      out.write("				                                							<option selected>선택</option>\r\n");
      out.write("				                                							<option>부모</option>\r\n");
      out.write("				                                							<option>자식</option>\r\n");
      out.write("				                                							<option>형제</option>\r\n");
      out.write("				                                							<option>조부모</option>\r\n");
      out.write("				                                						</select>\r\n");
      out.write("				                                					</td>\r\n");
      out.write("				                                					<td style=\"display:flex;\">\r\n");
      out.write("				                                						<div class=\"rdoBox\"><input type=\"radio\" id=\"seperate\" name=\"familytype\" value=\"분리세대\"><label for=\"seperate\" > 분리세대</label></div>\r\n");
      out.write("				                                						<div class=\"rdoBox\"><input type=\"radio\" id=\"same\" name=\"familytype\" value=\"동일세대\"><label for=\"same\" > 동일세대</label></div>\r\n");
      out.write("				                                					</td>\r\n");
      out.write("				                                			</tbody>\r\n");
      out.write("				                                		</table>\r\n");
      out.write("				                                	</div>	\r\n");
      out.write("				                                	<div class=\"detailBox\" >	\r\n");
      out.write("				                                		<div class=\"detailtitle\">\r\n");
      out.write("			                                				<div class=\"ititle\">가구원수</div>\r\n");
      out.write("			                                			</div>\r\n");
      out.write("				                                		<table class=\"detailinfotbl\">\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">가구원 수<br>(신청자·태아포함)</div></th>\r\n");
      out.write("				                                				<td><select>\r\n");
      out.write("			                                							<option selected>선택</option>\r\n");
      out.write("			                                							<option>1명</option>\r\n");
      out.write("			                                							<option>2명</option>\r\n");
      out.write("			                                							<option>3명</option>\r\n");
      out.write("			                                							<option>4명</option>\r\n");
      out.write("			                                							<option>5명</option>\r\n");
      out.write("			                                							<option>6명 이상</option>\r\n");
      out.write("			                                						</select>\r\n");
      out.write("			                                						<div>임신중인 태아가 있을 경우 <input type=\"button\" class=\"detailbtn\" value=\"태아수 입력\"> 버튼을 눌려주세요\r\n");
      out.write("			                                						<input type=\"text\" name=\"babycnt\" > 명</div>\r\n");
      out.write("			                                					</td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                		</table>\r\n");
      out.write("				                                		\r\n");
      out.write("				                                	</div>\r\n");
      out.write("				                                	<div class=\"detailBox\">	\r\n");
      out.write("				                                		<div class=\"detailtitle\">\r\n");
      out.write("			                                				<div class=\"ititle\">신청자 인적사항</div>\r\n");
      out.write("			                                			</div>\r\n");
      out.write("				                                		<input type=\"button\" value=\"회원가입정보와 동일\">\r\n");
      out.write("				                                		<table class=\"detailinfotbl\">\r\n");
      out.write("				                                		\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">신청자 이름</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">주민등록번호</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"rescode\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">주민등록상 주소</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"addrs\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">연락처</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"tel\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("				                                				<th><div class=\"icontent\">이메일</div></th>\r\n");
      out.write("				                                				<td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("				                                			</tr>\r\n");
      out.write("				                                			<tr>\r\n");
      out.write("			                                				<th><div class=\"icontent\">혼인여부</div></th>\r\n");
      out.write("				                                				<td>\r\n");
      out.write("				                                					<div style=\"border:1px solid #008485;\"><input type=\"radio\" id=\"재학생\" name=\"marry\" value=\"N\"><label for=\"재학생\"  class=\"ranktitle\"> 미혼</label></div>\r\n");
      out.write("				                                					<div style=\"border:1px solid #008485;\"><input type=\"radio\" id=\"복학예정\" name=\"marry\" value=\"Y\"><label for=\"복학예정\"  class=\"ranktitle\"> 기혼</label></div>\r\n");
      out.write("				                                				</td>\r\n");
      out.write("			                                				</tr>	\r\n");
      out.write("				                                		</table>\r\n");
      out.write("				                              		</div>\r\n");
      out.write("				                              </div>\r\n");
      out.write("			                                </div>\r\n");
      out.write("			                              <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("			                            </form>\r\n");
      out.write("			                        </div>\r\n");
      out.write("			                        <div role=\"tabpanel\" class=\"tab-pane\" id=\"profile\">Profile</div>\r\n");
      out.write("			                        <div role=\"tabpanel\" class=\"tab-pane\" id=\"messages\">Messages</div>\r\n");
      out.write("			                        <div role=\"tabpanel\" class=\"tab-pane\" id=\"settings\">Settings</div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                \r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/subscription/subscription.js\"></script>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/bottomMenu.jsp", out, false);
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
