/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-22 05:07:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/윤소영/final-project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HomeOneHana/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629721598702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>HomeOneHana</title>\r\n");
      out.write("    </head>\r\n");
      out.write("	<body data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"51\">\r\n");
      out.write("        <!-- Nav Bar Start -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- Nav Bar End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Hero Start -->\r\n");
      out.write("        <div class=\"hero\" id=\"home\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-sm-12 col-md-6\">\r\n");
      out.write("                        <div class=\"hero-content\">\r\n");
      out.write("                            <div class=\"hero-text\">\r\n");
      out.write("                            	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <h2></h2>\r\n");
      out.write("                                <div class=\"typed-text\">행복주택, 공공임대, 매입임대, 전세임대, 국민임대</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hero-btn\">\r\n");
      out.write("                            	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-12 col-md-6 d-none d-md-block\">\r\n");
      out.write("                        <div class=\"hero-image\" style=\"width:421px; height:600px;\">\r\n");
      out.write("                            <!-- <img src=\"img/hero.png\" alt=\"Hero Image\"> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Hero End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Latest Announcement Start -->\r\n");
      out.write("        <div class=\"portfolio\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>Announcement</p>\r\n");
      out.write("                    <h2>Today's News</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <ul id=\"portfolio-filter\">\r\n");
      out.write("                            <li data-filter=\"*\" class=\"filter-active\">전체</li>\r\n");
      out.write("                            <li data-filter=\".filter-1\">행복주택</li>\r\n");
      out.write("                            <li data-filter=\".filter-2\">매입임대</li>\r\n");
      out.write("                            <li data-filter=\".filter-3\">국민임대</li>\r\n");
      out.write("                            <li data-filter=\".filter-4\">전세임대</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row portfolio-container\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-1 wow fadeInUp\" data-wow-delay=\"0.0s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-1.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>eCommerce Website</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-1.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-2 wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-2.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>Product Landing Page</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-2.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-3 wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-3.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>JavaScript quiz game</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-3.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-1 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-4.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>JavaScript drawing</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-4.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-2 wow fadeInUp\" data-wow-delay=\"0.8s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-5.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>Social Mobile Apps</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-5.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 col-sm-12 portfolio-item filter-4 wow fadeInUp\" data-wow-delay=\"1s\">\r\n");
      out.write("                        <div class=\"portfolio-wrap\">\r\n");
      out.write("                            <div class=\"portfolio-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-6.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"portfolio-text\">\r\n");
      out.write("                                <h3>Company Website</h3>\r\n");
      out.write("                                <a class=\"btn\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/portfolio-6.jpg\" data-lightbox=\"portfolio\">+</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Latest Announcement End -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Banner Start -->\r\n");
      out.write("        <div class=\"banner wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center\">\r\n");
      out.write("                    <p>Reasonable Price</p>\r\n");
      out.write("                    <h2>Get A <span>Special</span> Price</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"container banner-text\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <a class=\"btn\">Pricing Plan</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Banner End -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- About Start -->\r\n");
      out.write("        <div class=\"about wow fadeInUp\" data-wow-delay=\"0.1s\" id=\"about\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"about-img\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/about.jpg\" alt=\"Image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"about-content\">\r\n");
      out.write("                            <div class=\"section-header text-left\">\r\n");
      out.write("                                <p>Learn About Me</p>\r\n");
      out.write("                                <h2>10 Years Experience</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"about-text\">\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"skills\">\r\n");
      out.write("                                <div class=\"skill-name\">\r\n");
      out.write("                                    <p>Web Design</p><p>85%</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"85\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"skill-name\">\r\n");
      out.write("                                    <p>Web Development</p><p>95%</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"95\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"skill-name\">\r\n");
      out.write("                                    <p>Apps Design</p><p>90%</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"skill-name\">\r\n");
      out.write("                                    <p>Apps Development</p><p>85%</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"progress\">\r\n");
      out.write("                                    <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"85\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"btn\" href=\"\">Learn More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- About End -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Service Start -->\r\n");
      out.write("        <div class=\"service\" id=\"service\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>YOU CAN FIND</p>\r\n");
      out.write("                    <h2>Home Type</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.0s\">\r\n");
      out.write("                        <div class=\"service-item\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"far fa-smile\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h3>행복주택</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    청년(19세∼39세·신혼부부·대학생 등 젊은계층의 주거불안 해소를 위해 국가 재정과 주택도시기금을 지원받아 대중교통이 편리한 부지에 주변시세보다 저렴하게 공급하는 공공임대주택\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        <div class=\"service-item\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-building\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h3>매입임대</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    주거부담이 큰 월세 거주비율이 높은 청년·신혼부부를 대상으로 주택도시기금이 기존 주택을 매입한 후, LH가 시세의 90%이하로 공급하는 임대주택\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                        <div class=\"service-item\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-heart\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h3>전세임대</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    도심 내 저소득계층 등이 현 생활권에서 거주할 수 있도록 대상자가 거주를 원하는 주택을 물색하면 LH가 전세계약을 체결한 후 저렴하게 재임대하는 공공임대주택\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                        <div class=\"service-item\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-home\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h3>국민임대</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    장기 공공임대주택 재고량을 선진국 수준으로 확대하여 무주택 저소득(소득1∼4분위 계층)의 주거안정을 도모하기 위해 건설·공급하는 공공임대주택\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Service End -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         <!-- Experience Start -->\r\n");
      out.write("        <div class=\"experience\" id=\"experience\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <header class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>About Policy</p>\r\n");
      out.write("                    <h2>Residential Ladder Policy</h2>\r\n");
      out.write("                </header>\r\n");
      out.write("                <div class=\"timeline\">\r\n");
      out.write("                    <div class=\"timeline-item left wow slideInLeft\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>장기전세</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"timeline-item right wow slideInRight\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>행복주택</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"timeline-item left wow slideInLeft\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>국민임대</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"timeline-item right wow slideInRight\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>재개발임대</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"timeline-item left wow slideInLeft\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>매입임대</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"timeline-item right wow slideInRight\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                        <div class=\"timeline-text\">\r\n");
      out.write("                            <div class=\"timeline-date\">2045 - 2050</div>\r\n");
      out.write("                            <h2>영구임대</h2>\r\n");
      out.write("                            <h4>Soft Agency, San Francisco, CA</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet elit. Aliquam odio dolor, id luctus erat sagittis non. Ut blandit semper pretium.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Job Experience End -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- Banner Start -->\r\n");
      out.write("        <div class=\"banner wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center\">\r\n");
      out.write("                    <p>Awesome Discount</p>\r\n");
      out.write("                    <h2>Get <span>30%</span> Discount</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"container banner-text\">\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <a class=\"btn\">Order Now</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Banner End -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Price Start -->\r\n");
      out.write("        <div class=\"price\" id=\"price\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>Pricing Plan</p>\r\n");
      out.write("                    <h2>Affordable Price</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                        <div class=\"price-item\">\r\n");
      out.write("                            <div class=\"price-header\">\r\n");
      out.write("                                <div class=\"price-title\">\r\n");
      out.write("                                    <h2>Basic</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"price-prices\">\r\n");
      out.write("                                    <h2><small>$</small>49<span>/ mo</span></h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-body\">\r\n");
      out.write("                                <div class=\"price-description\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>Bootstrap 4</li>\r\n");
      out.write("                                        <li>Font Awesome 5</li>\r\n");
      out.write("                                        <li>Responsive Design</li>\r\n");
      out.write("                                        <li>Browser Compatibility</li>\r\n");
      out.write("                                        <li>Easy To Use</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-footer\">\r\n");
      out.write("                                <div class=\"price-action\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\">Order Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 wow fadeInUp\" data-wow-delay=\"0.0s\">\r\n");
      out.write("                        <div class=\"price-item featured-item\">\r\n");
      out.write("                            <div class=\"price-header\">\r\n");
      out.write("                                <div class=\"price-title\">\r\n");
      out.write("                                    <h2>Standard</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"price-prices\">\r\n");
      out.write("                                    <h2><small>$</small>99<span>/ mo</span></h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-body\">\r\n");
      out.write("                                <div class=\"price-description\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>Bootstrap 4</li>\r\n");
      out.write("                                        <li>Font Awesome 5</li>\r\n");
      out.write("                                        <li>Responsive Design</li>\r\n");
      out.write("                                        <li>Browser Compatibility</li>\r\n");
      out.write("                                        <li>Easy To Use</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-footer\">\r\n");
      out.write("                                <div class=\"price-action\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\">Order Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                        <div class=\"price-item\">\r\n");
      out.write("                            <div class=\"price-header\">\r\n");
      out.write("                                <div class=\"price-title\">\r\n");
      out.write("                                    <h2>Premium</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"price-prices\">\r\n");
      out.write("                                    <h2><small>$</small>149<span>/ mo</span></h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-body\">\r\n");
      out.write("                                <div class=\"price-description\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>Bootstrap 4</li>\r\n");
      out.write("                                        <li>Font Awesome 5</li>\r\n");
      out.write("                                        <li>Responsive Design</li>\r\n");
      out.write("                                        <li>Browser Compatibility</li>\r\n");
      out.write("                                        <li>Easy To Use</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-footer\">\r\n");
      out.write("                                <div class=\"price-action\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\">Order Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Price End -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Testimonial Start -->\r\n");
      out.write("        <div class=\"testimonial wow fadeInUp\" data-wow-delay=\"0.1s\" id=\"review\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"testimonial-icon\">\r\n");
      out.write("                    <i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-carousel testimonials-carousel\">\r\n");
      out.write("                    <div class=\"testimonial-item\">\r\n");
      out.write("                        <div class=\"testimonial-img\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/testimonial-1.jpg\" alt=\"Image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"testimonial-text\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet consec adipis elit. Etiam accums lacus eget velit tincid, quis suscip justo dictum. Lorem ipsum dolor sit amet consec adipis elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <h3>Customer Name</h3>\r\n");
      out.write("                            <h4>Profession</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"testimonial-item\">\r\n");
      out.write("                        <div class=\"testimonial-img\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/testimonial-2.jpg\" alt=\"Image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"testimonial-text\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet consec adipis elit. Etiam accums lacus eget velit tincid, quis suscip justo dictum. Lorem ipsum dolor sit amet consec adipis elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <h3>Customer Name</h3>\r\n");
      out.write("                            <h4>Profession</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"testimonial-item\">\r\n");
      out.write("                        <div class=\"testimonial-img\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/testimonial-3.jpg\" alt=\"Image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"testimonial-text\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum dolor sit amet consec adipis elit. Etiam accums lacus eget velit tincid, quis suscip justo dictum. Lorem ipsum dolor sit amet consec adipis elit.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <h3>Customer Name</h3>\r\n");
      out.write("                            <h4>Profession</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Team Start -->\r\n");
      out.write("        <div class=\"team\" id=\"team\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>My Team</p>\r\n");
      out.write("                    <h2>Expert Team Members</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.0s\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/team-1.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text\">\r\n");
      out.write("                                <h2>Mollie Ross</h2>\r\n");
      out.write("                                <h4>Web Designer</h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"team-social\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/team-2.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text\">\r\n");
      out.write("                                <h2>Dylan Adams</h2>\r\n");
      out.write("                                <h4>Web Developer</h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"team-social\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/team-3.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text\">\r\n");
      out.write("                                <h2>Jennifer Page</h2>\r\n");
      out.write("                                <h4>Apps Designer</h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"team-social\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img\">\r\n");
      out.write("                                <img src=\"img/team-4.jpg\" alt=\"Image\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text\">\r\n");
      out.write("                                <h2>Josh Dunn</h2>\r\n");
      out.write("                                <h4>Apps Developer</h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"team-social\">\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                    <a class=\"btn\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Team End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Blog Start -->\r\n");
      out.write("        <div class=\"blog\" id=\"blog\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"section-header text-center wow zoomIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <p>From Blog</p>\r\n");
      out.write("                    <h2>Latest Articles</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"blog-item wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                            <div class=\"blog-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/blog-1.jpg\" alt=\"Blog\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog-text\">\r\n");
      out.write("                                <h2>Lorem ipsum dolor sit amet</h2>\r\n");
      out.write("                                <div class=\"blog-meta\">\r\n");
      out.write("                                    <p><i class=\"far fa-user\"></i>Admin</p>\r\n");
      out.write("                                    <p><i class=\"far fa-list-alt\"></i>Web Design</p>\r\n");
      out.write("                                    <p><i class=\"far fa-calendar-alt\"></i>01-Jan-2045</p>\r\n");
      out.write("                                    <p><i class=\"far fa-comments\"></i>5</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet elit. Nullam commodo mattis mi. Nullam eu erat lectus. Proin viverra risus vitae luctus. Proin ut ante, vitae sapien. Fusce sem ac erat rhoncus, ornare mattis nisl massa et eros vitae pulvin\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <a class=\"btn\" href=\"\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"blog-item wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                            <div class=\"blog-img\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/home/blog-2.jpg\" alt=\"Blog\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog-text\">\r\n");
      out.write("                                <h2>Lorem ipsum dolor sit amet</h2>\r\n");
      out.write("                                <div class=\"blog-meta\">\r\n");
      out.write("                                    <p><i class=\"far fa-user\"></i>Admin</p>\r\n");
      out.write("                                    <p><i class=\"far fa-list-alt\"></i>Apps Design</p>\r\n");
      out.write("                                    <p><i class=\"far fa-calendar-alt\"></i>01-Jan-2045</p>\r\n");
      out.write("                                    <p><i class=\"far fa-comments\"></i>10</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    Lorem ipsum dolor sit amet elit. Nullam commodo mattis mi. Nullam eu erat lectus. Proin viverra risus vitae luctus. Proin ut ante, vitae sapien. Fusce sem ac erat rhoncus, ornare mattis nisl massa et eros vitae pulvin\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <a class=\"btn\" href=\"\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Blog End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer Start -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/bottomMenu.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(22,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                                <p>전국 모든 임대주택을 한 눈에!</p>\r\n");
          out.write("	                                <h1>Home One Hana</h1>                            	\r\n");
          out.write("                            	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/index.jsp(26,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty sessionScope.loginVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            		<p>전국 모든 임대주택을 한 눈에!</p>\r\n");
          out.write("	                                <h1>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</h1> \r\n");
          out.write("                            	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/index.jsp(28,37) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginVO.name }님 환영합니다!", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/index.jsp(34,29) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <a class=\"btn\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">Log In</a>\r\n");
          out.write("                                <a class=\"btn\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/signup\">Join</a>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
